// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2EOsivzRySzcCj4EbYkfny8gWBl3pG6A',
    appId: '1:438822396987:web:201d7e16c5e83d80c2681e',
    messagingSenderId: '438822396987',
    projectId: 'personal-app-fe948',
    authDomain: 'personal-app-fe948.firebaseapp.com',
    storageBucket: 'personal-app-fe948.appspot.com',
    measurementId: 'G-5VD8RBWH1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-yLLnFjxy7wVZhJn5r2tk8kNZV4wchv4',
    appId: '1:438822396987:android:74ef657bb4aaa5a7c2681e',
    messagingSenderId: '438822396987',
    projectId: 'personal-app-fe948',
    storageBucket: 'personal-app-fe948.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC8sjzPNYfKn6zlG0a-RuHOdgc5yYA8hw',
    appId: '1:438822396987:ios:0a89d040b051f2bec2681e',
    messagingSenderId: '438822396987',
    projectId: 'personal-app-fe948',
    storageBucket: 'personal-app-fe948.appspot.com',
    iosBundleId: 'com.example.personalFrontend',
  );
}
